language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
- 4
script: npm run lint && npm run flow_check && npm run test:travis
deploy:
  skip_cleanup: true
  provider: npm
  email: shaun.stanworth@googlemail.com
  api_key:
    secure: SKmHxNRZl6Z/ngGYIXe6QnRC+n83wbN83WgOZlmrPItxM+0dd23oIdMVpxoKKPFcggQBZD7XKib6v/4LoreQSYjLgm72ycuE3vlMnNHx0guJHq3xPk4RdoYjvp7IbPXRVbZooUuxJTFvtu0HHD0LeQxhrHmJ+l9iX6oe2vcgJO2dSm2lgxD3ts402vwB67KH9rWoQFGsXNQv2Y9yP5Ij62ETqrYVlscw4Rwjz7XXdOJ8Tv4bLLh58dxjCUcLXOZFS3AZ3l5E/0tj2e7THktk4Xa9b3KsHMvefwCeSO9khoSRJj5606PaxCzWYo8UtMm+KXeufcQgabokNvJBmrQ4Ih+t684Jxas60pFF+d2RRk0AKK6mAqZmTxD/0TI0PQVZAw7D63u3u40YaeMLp6JgRmLUUXjUuzaCeDv4VZvmI6EhCRdlbvn4+275IwfyIDWGCH3IEf4BGIatHxgjX/84EGqGYC02e1dS1LOncp8mEpvQKBXZZGFCpVdH233XYVkya85lapiAlfFSAXtHegGKUcOYDCcyr6/bml15BcBjpEBlj6jqKYV67UQHc+geiXOq9PrLZCSc2pl6a/dW86+3s0Lr07dZjz+UG6KOEnPjHSPYnhfnZN7ajUlmDRGuP+sis8FQbEedDY6Frp/XjBzJ7zmcMInLh078fuhUTJsnEhA=
  on:
    repo: smartive/smartive-react-d3-radar
    branch: master
